public final class ad {
   public int A = -1;
   public int B = -1;
   public int C = -1;
   public int D = -1;
   public int E = -1;
   public int F = -1;
   public int G = 0;
   public int H = -1;
   public int I = -1;
   public int J = -1;
   public int K = -1;
   public int L = -1;
   public int M = -1;
   public float N = 0.0F;
   public float O = 0.0F;
   public int P = 0;
   public int Q = 0;
   public float R = 1.0F;
   public boolean S = false;
   public float T = 0.0F;
   public float U = 0.0F;
   public float V = 0.0F;
   public float W = 1.0F;
   public float X = 1.0F;
   public float Y = 0.0F;
   public float Z = 0.0F;
   boolean a = false;
   public float aa = 0.0F;
   public float ab = 0.0F;
   public float ac = 0.0F;
   public int ad = -1;
   public int ae = -1;
   public int af = -1;
   public int ag = -1;
   public int ah = -1;
   public int ai = -1;
   public int b;
   public int c;
   public int d;
   public int e = -1;
   public int f = -1;
   public float g = -1.0F;
   public int h = -1;
   public int i = -1;
   public int j = -1;
   public int k = -1;
   public int l = -1;
   public int m = -1;
   public int n = -1;
   public int o = -1;
   public int p = -1;
   public int q = -1;
   public int r = -1;
   public int s = -1;
   public int t = -1;
   public float u = 0.5F;
   public float v = 0.5F;
   public String w = null;
   public int x = -1;
   public int y = -1;
   public int z = -1;

   public final void a(ac var1) {
      var1.d = this.h;
      var1.e = this.i;
      var1.f = this.j;
      var1.g = this.k;
      var1.h = this.l;
      var1.i = this.m;
      var1.j = this.n;
      var1.k = this.o;
      var1.l = this.p;
      var1.m = this.q;
      var1.n = this.r;
      var1.o = this.s;
      var1.p = this.t;
      var1.leftMargin = this.A;
      var1.rightMargin = this.B;
      var1.topMargin = this.C;
      var1.bottomMargin = this.D;
      var1.u = this.M;
      var1.v = this.L;
      var1.w = this.u;
      var1.x = this.v;
      var1.y = this.w;
      var1.K = this.x;
      var1.L = this.y;
      var1.B = this.N;
      var1.A = this.O;
      var1.D = this.Q;
      var1.C = this.P;
      var1.E = this.ad;
      var1.F = this.ae;
      var1.I = this.af;
      var1.J = this.ag;
      var1.G = this.ah;
      var1.H = this.ai;
      var1.M = this.z;
      var1.c = this.g;
      var1.a = this.e;
      var1.b = this.f;
      var1.width = this.b;
      var1.height = this.c;
      var1.setMarginStart(this.F);
      var1.setMarginEnd(this.E);
      var1.a();
   }
}
