public final class arx {
   public static final long A;
   public static final long B;
   public static final long C;
   public static final long D;
   public static final long E;
   public static final long F;
   public static final long G;
   public static final long H;
   public static final long I;
   public static final long a;
   public static final long b;
   public static final long c;
   public static final long d;
   public static final long e;
   public static final long f;
   public static final long g;
   public static final long h;
   public static final long i;
   public static final long j;
   public static final long k;
   public static final long l;
   public static final long m;
   public static final long n;
   public static final long o;
   public static final long p;
   public static final long q;
   public static final long r;
   public static final long s;
   public static final long t;
   public static final long u;
   public static final long v;
   public static final long w;
   public static final long x;
   public static final long y;
   public static final long z;

   static {
      long var0 = ary.a;
      long var2 = ary.u;
      a = var2;
      b = ary.c;
      c = ary.d;
      d = ary.r;
      e = ary.C;
      f = ary.j;
      var0 = ary.f;
      g = var0;
      h = ary.b;
      i = ary.a;
      j = ary.A;
      k = ary.z;
      l = ary.F;
      m = ary.E;
      n = var0;
      o = ary.v;
      p = ary.J;
      q = ary.I;
      r = ary.w;
      s = ary.x;
      t = ary.B;
      u = ary.D;
      v = ary.e;
      w = ary.G;
      x = ary.H;
      y = var2;
      z = ary.t;
      A = ary.q;
      B = ary.p;
      C = ary.o;
      D = ary.s;
      E = ary.g;
      F = ary.n;
      G = ary.y;
      H = ary.K;
      I = ary.L;
   }
}
