public final class asa {
   public static final long A;
   public static final long B;
   public static final long C;
   public static final bvc D;
   public static final bvd E;
   public static final long F;
   public static final long G;
   public static final long H;
   public static final bvc I;
   public static final bvd J;
   public static final long K;
   public static final long L;
   public static final long M;
   public static final bvc N;
   public static final bvd O;
   public static final long P;
   public static final long Q;
   public static final long R;
   public static final bvc S;
   public static final bvd T;
   public static final long U;
   public static final long V;
   public static final long W;
   public static final bvc X;
   public static final bvd Y;
   public static final long Z;
   public static final bvd a;
   public static final long aa;
   public static final long ab;
   public static final bvc ac;
   public static final bvd ad;
   public static final long ae;
   public static final long af;
   public static final long ag;
   public static final bvc ah;
   public static final bvd ai;
   public static final long aj;
   public static final long ak;
   public static final long al;
   public static final bvc am;
   public static final bvd an;
   public static final long ao;
   public static final long ap;
   public static final long aq;
   public static final bvc ar;
   public static final bvd as;
   public static final long at;
   public static final long au;
   public static final long av;
   public static final bvc aw;
   public static final long b;
   public static final long c;
   public static final long d;
   public static final bvc e;
   public static final bvd f;
   public static final long g;
   public static final long h;
   public static final long i;
   public static final bvc j;
   public static final bvd k;
   public static final long l;
   public static final long m;
   public static final long n;
   public static final bvc o;
   public static final bvd p;
   public static final long q;
   public static final long r;
   public static final long s;
   public static final bvc t;
   public static final bvd u;
   public static final long v;
   public static final long w;
   public static final long x;
   public static final bvc y;
   public static final bvd z;

   static {
      bvd var2 = asb.a;
      a = asb.b;
      b = car.C(24.0D);
      c = car.E(16);
      d = car.C(0.5D);
      e = asb.d;
      f = asb.b;
      g = car.C(20.0D);
      h = car.E(14);
      i = car.C(0.2D);
      j = asb.d;
      k = asb.b;
      l = car.C(16.0D);
      m = car.E(12);
      n = car.C(0.4D);
      o = asb.d;
      p = asb.a;
      q = car.C(64.0D);
      r = car.E(57);
      long var0 = car.C(0.2D);
      if (!car.G(var0)) {
         s = car.F(bxz.b(var0), -bxz.a(var0));
         t = asb.d;
         u = asb.a;
         v = car.C(52.0D);
         w = car.E(45);
         x = car.C(0.0D);
         y = asb.d;
         z = asb.a;
         A = car.C(44.0D);
         B = car.E(36);
         C = car.C(0.0D);
         D = asb.d;
         E = asb.a;
         F = car.C(40.0D);
         G = car.E(32);
         H = car.C(0.0D);
         I = asb.d;
         J = asb.a;
         K = car.C(36.0D);
         L = car.E(28);
         M = car.C(0.0D);
         N = asb.d;
         O = asb.a;
         P = car.C(32.0D);
         Q = car.E(24);
         R = car.C(0.0D);
         S = asb.d;
         T = asb.b;
         U = car.C(20.0D);
         V = car.E(14);
         W = car.C(0.1D);
         X = asb.c;
         Y = asb.b;
         Z = car.C(16.0D);
         aa = car.E(12);
         ab = car.C(0.5D);
         ac = asb.c;
         ad = asb.b;
         ae = car.C(16.0D);
         af = car.E(11);
         ag = car.C(0.5D);
         ah = asb.c;
         ai = asb.a;
         aj = car.C(28.0D);
         ak = car.E(22);
         al = car.C(0.0D);
         am = asb.d;
         an = asb.b;
         ao = car.C(24.0D);
         ap = car.E(16);
         aq = car.C(0.2D);
         ar = asb.c;
         as = asb.b;
         at = car.C(20.0D);
         au = car.E(14);
         av = car.C(0.1D);
         aw = asb.c;
      } else {
         throw new IllegalArgumentException("Cannot perform operation for Unspecified type.");
      }
   }
}
