package com.google.lens.sdk;

public @interface LensApi$LensAvailabilityStatus {
   int LENS_AVAILABILITY_UNKNOWN = -1;
   int LENS_READY = 0;
   int LENS_UNAVAILABLE = 1;
   int LENS_UNAVAILABLE_AGSA_OUTDATED = 6;
   @Deprecated
   int LENS_UNAVAILABLE_ASSISTANT_EYES_FLAG_DISABLED = 8;
   int LENS_UNAVAILABLE_DEVICE_INCOMPATIBLE = 3;
   int LENS_UNAVAILABLE_DEVICE_LOCKED = 5;
   int LENS_UNAVAILABLE_FEATURE_UNAVAILABLE = 11;
   int LENS_UNAVAILABLE_INVALID_CURSOR = 4;
   @Deprecated
   int LENS_UNAVAILABLE_LOCALE_NOT_SUPPORTED = 2;
   int LENS_UNAVAILABLE_SERVICE_BUSY_FAILURE = 10;
   int LENS_UNAVAILABLE_SERVICE_UNAVAILABLE = 9;
   int LENS_UNAVAILABLE_UNKNOWN_ERROR_CODE = 12;
}
